all:
	mkdir bin
	cp src/parser_yacc.py bin/parser_yacc.py
	cp src/lexer_yacc.py bin/lexer_yacc.py
	cp src/script.py bin/script.py
	cp src/script.sh bin/script.sh
	cp src/script.py script.py
	cp src/script.sh script.sh
	cp src/symbol.py bin/symbol.py
	cp src/tac.py bin/tac.py

clean:
	rm -rf bin out.ps parselog3.txt parselog.txt parser.out parsetab.py parse_tree.dot script.py script.sh

	